/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btl_java;

/**
 *
 * @author Admin
 */
public class mainInterface extends javax.swing.JFrame {

    /**
     * Creates new form mainInterface
     */
    String user;
    public mainInterface() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ql_khachhang = new javax.swing.JButton();
        bt_ql_sanpham = new javax.swing.JButton();
        btn_ql_hangton = new javax.swing.JButton();
        btn_ql_nhap_xuat = new javax.swing.JButton();
        btn_qlnv = new javax.swing.JButton();
        btn_baocaodoanhthu = new javax.swing.JButton();
        tf_taikhoanX = new javax.swing.JLabel();
        btn_dangxuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        btn_ql_khachhang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_ql_khachhang.setText("Quản lý khách hàng");
        btn_ql_khachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ql_khachhangActionPerformed(evt);
            }
        });

        bt_ql_sanpham.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bt_ql_sanpham.setText("Quản lý sản phẩm");
        bt_ql_sanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ql_sanphamActionPerformed(evt);
            }
        });

        btn_ql_hangton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_ql_hangton.setText("Quản lý hàng tồn");
        btn_ql_hangton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ql_hangtonActionPerformed(evt);
            }
        });

        btn_ql_nhap_xuat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_ql_nhap_xuat.setText("Quản lý hóa đơn nhập, xuất");
        btn_ql_nhap_xuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ql_nhap_xuatActionPerformed(evt);
            }
        });

        btn_qlnv.setText("QUẢN LÝ NHÂN VIÊN");
        btn_qlnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlnvActionPerformed(evt);
            }
        });

        btn_baocaodoanhthu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_baocaodoanhthu.setText("Báo cáo doanh thu");
        btn_baocaodoanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_baocaodoanhthuActionPerformed(evt);
            }
        });

        tf_taikhoanX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tf_taikhoanX.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_dangxuat.setText("Đăng xuất");
        btn_dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangxuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_ql_khachhang, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                .addComponent(bt_ql_sanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btn_qlnv, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_ql_nhap_xuat, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_ql_hangton, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_baocaodoanhthu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(tf_taikhoanX, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btn_dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_taikhoanX, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btn_dangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_ql_sanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ql_nhap_xuat, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_qlnv, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ql_hangton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_ql_khachhang, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(btn_baocaodoanhthu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ql_khachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ql_khachhangActionPerformed
        this.setVisible(false);
        new QLKhachHang().setVisible(true);
    }//GEN-LAST:event_btn_ql_khachhangActionPerformed

    private void bt_ql_sanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ql_sanphamActionPerformed
        this.setVisible(false);
        new QLSanPham().setVisible(true);
    }//GEN-LAST:event_bt_ql_sanphamActionPerformed

    private void btn_ql_nhap_xuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ql_nhap_xuatActionPerformed
       this.setVisible(false);
        new QLNhap_Xuat().setVisible(true);
    }//GEN-LAST:event_btn_ql_nhap_xuatActionPerformed

    private void btn_ql_hangtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ql_hangtonActionPerformed
        this.setVisible(false);
        new QLHangTon().setVisible(true);
    }//GEN-LAST:event_btn_ql_hangtonActionPerformed

    private void btn_qlnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlnvActionPerformed
        this.setVisible(false);
        new QLNHANVIEN().setVisible(true);
    }//GEN-LAST:event_btn_qlnvActionPerformed

    private void btn_baocaodoanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_baocaodoanhthuActionPerformed
        this.setVisible(false);
        new Thongke().setVisible(true);
    }//GEN-LAST:event_btn_baocaodoanhthuActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
       
        tf_taikhoanX.setText("Xin chào! ");
        
        
    }//GEN-LAST:event_formComponentShown

    private void btn_dangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangxuatActionPerformed
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btn_dangxuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ql_sanpham;
    private javax.swing.JButton btn_baocaodoanhthu;
    private javax.swing.JButton btn_dangxuat;
    private javax.swing.JButton btn_ql_hangton;
    private javax.swing.JButton btn_ql_khachhang;
    private javax.swing.JButton btn_ql_nhap_xuat;
    private javax.swing.JButton btn_qlnv;
    private javax.swing.JLabel tf_taikhoanX;
    // End of variables declaration//GEN-END:variables
}
