/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btl_java;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class QLDonDh extends javax.swing.JFrame {

    /**
     * Creates new form QLHoaDon
     */
    public QLDonDh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_dondh = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_sohd = new javax.swing.JTextField();
        tf_ngaydh = new javax.swing.JTextField();
        btn_them_dondh = new javax.swing.JButton();
        btn_update_dondh = new javax.swing.JButton();
        btn_xoa_dondh = new javax.swing.JButton();
        btn_tim_dondh = new javax.swing.JButton();
        jcb_tenncc = new javax.swing.JComboBox();
        btn_dulieugoc_dondh = new javax.swing.JButton();
        btn_thoat_ctdondh1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_ctdondh = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_soluongdat = new javax.swing.JTextField();
        btn_them_ctdondh = new javax.swing.JButton();
        btn_update_ctdondh = new javax.swing.JButton();
        btn_delete_ctdondh = new javax.swing.JButton();
        btn_dulieugoc_ctdondh = new javax.swing.JButton();
        jcb_tenhang = new javax.swing.JComboBox();
        jcb_sodh = new javax.swing.JComboBox();
        btn_thoat_ctdondh = new javax.swing.JButton();
        btn_tim_sodh = new javax.swing.JButton();
        btn_tim_tenhang = new javax.swing.JButton();
        btn_tim_soDH_tenHang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        table_dondh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số đơn hàng", "Ngày đặt hàng", "Tên NCC"
            }
        ));
        table_dondh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_dondhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_dondh);

        jLabel1.setText("Số hóa đơn");

        jLabel3.setText("Ngày đặt hàng");

        jLabel4.setText("Tên NCC");

        btn_them_dondh.setText("Thêm");
        btn_them_dondh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_them_dondhActionPerformed(evt);
            }
        });

        btn_update_dondh.setText("Sửa");
        btn_update_dondh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_dondhActionPerformed(evt);
            }
        });

        btn_xoa_dondh.setText("Xóa");
        btn_xoa_dondh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoa_dondhActionPerformed(evt);
            }
        });

        btn_tim_dondh.setText("Tìm kiếm");
        btn_tim_dondh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tim_dondhActionPerformed(evt);
            }
        });

        btn_dulieugoc_dondh.setText("Dữ liệu gốc");
        btn_dulieugoc_dondh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dulieugoc_dondhActionPerformed(evt);
            }
        });

        btn_thoat_ctdondh1.setText("Thoát");
        btn_thoat_ctdondh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoat_ctdondh1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btn_them_dondh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_update_dondh))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(tf_sohd, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_ngaydh, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(jcb_tenncc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btn_xoa_dondh)
                        .addGap(77, 77, 77)
                        .addComponent(btn_tim_dondh)
                        .addGap(39, 39, 39)
                        .addComponent(btn_dulieugoc_dondh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btn_thoat_ctdondh1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(134, 134, 134))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(tf_sohd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ngaydh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcb_tenncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them_dondh)
                    .addComponent(btn_update_dondh)
                    .addComponent(btn_xoa_dondh)
                    .addComponent(btn_tim_dondh)
                    .addComponent(btn_dulieugoc_dondh)
                    .addComponent(btn_thoat_ctdondh1))
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Đơn đặt hàng", jPanel1);

        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });

        table_ctdondh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số đơn hàng", "Tên hàng", "Số lượng đặt"
            }
        ));
        table_ctdondh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_ctdondhMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_ctdondh);

        jLabel5.setText("Số đơn hàng");

        jLabel6.setText("Tên hàng");

        jLabel7.setText("Số lượng đặt");

        btn_them_ctdondh.setText("Thêm");
        btn_them_ctdondh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_them_ctdondhActionPerformed(evt);
            }
        });

        btn_update_ctdondh.setText("Sửa");
        btn_update_ctdondh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_ctdondhActionPerformed(evt);
            }
        });

        btn_delete_ctdondh.setText("Xóa");
        btn_delete_ctdondh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_ctdondhActionPerformed(evt);
            }
        });

        btn_dulieugoc_ctdondh.setText("Dữ liệu gốc");
        btn_dulieugoc_ctdondh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dulieugoc_ctdondhActionPerformed(evt);
            }
        });

        btn_thoat_ctdondh.setText("Thoát");
        btn_thoat_ctdondh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoat_ctdondhActionPerformed(evt);
            }
        });

        btn_tim_sodh.setText("Lọc theo số ĐH");
        btn_tim_sodh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tim_sodhActionPerformed(evt);
            }
        });

        btn_tim_tenhang.setText("Lọc theo tên hàng");
        btn_tim_tenhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tim_tenhangActionPerformed(evt);
            }
        });

        btn_tim_soDH_tenHang.setText("Lọc theo Số Đh và tên hàng");
        btn_tim_soDH_tenHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tim_soDH_tenHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_soluongdat, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jcb_tenhang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcb_sodh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_tim_tenhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_tim_sodh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_tim_soDH_tenHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_them_ctdondh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_update_ctdondh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_dulieugoc_ctdondh, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_delete_ctdondh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_thoat_ctdondh, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btn_them_ctdondh)
                    .addComponent(btn_delete_ctdondh)
                    .addComponent(jcb_sodh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tim_sodh))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcb_tenhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tim_tenhang)
                    .addComponent(btn_update_ctdondh))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_dulieugoc_ctdondh)
                    .addComponent(tf_soluongdat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(btn_tim_soDH_tenHang)
                    .addComponent(btn_thoat_ctdondh))
                .addGap(46, 46, 46))
        );

        jTabbedPane1.addTab("Chi tiết đơn đặt hàng", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        DefaultTableModel tbn = (DefaultTableModel) table_dondh.getModel();
        tbn.setRowCount(0);
        jcb_tenncc.removeAllItems();
        Form_load_TenNhaCc();
        hienthi();
    }//GEN-LAST:event_jPanel1ComponentShown

    private void btn_dulieugoc_dondhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dulieugoc_dondhActionPerformed
        DefaultTableModel tbn = (DefaultTableModel) table_dondh.getModel();
        tbn.setRowCount(0);
        jcb_tenncc.removeAllItems();
        Form_load_TenNhaCc();
        hienthi();
    }//GEN-LAST:event_btn_dulieugoc_dondhActionPerformed

    private void table_dondhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_dondhMouseClicked
        try {
            int index = table_dondh.getSelectedRow();
            tf_sohd.setText(table_dondh.getValueAt(index, 0).toString());
            SimpleDateFormat formatter = new SimpleDateFormat("dd/mm/yyyy");
            Date date = new SimpleDateFormat("yyyy-mm-dd").parse(table_dondh.getValueAt(index, 1).toString());
            String strDate = formatter.format(date);
            tf_ngaydh.setText(strDate);
            jcb_tenncc.setSelectedItem(table_dondh.getValueAt(index, 2));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_table_dondhMouseClicked

    private void btn_them_dondhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_them_dondhActionPerformed
        Add_DONDH();
    }//GEN-LAST:event_btn_them_dondhActionPerformed

    private void btn_update_dondhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_dondhActionPerformed
        Update_DONDH();
    }//GEN-LAST:event_btn_update_dondhActionPerformed

    private void btn_xoa_dondhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoa_dondhActionPerformed
        Delete_DONDH();
    }//GEN-LAST:event_btn_xoa_dondhActionPerformed

    private void btn_tim_dondhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tim_dondhActionPerformed
        this.setVisible(false);
        new Timkiem_DONDH().setVisible(true);
    }//GEN-LAST:event_btn_tim_dondhActionPerformed

    private void btn_dulieugoc_ctdondhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dulieugoc_ctdondhActionPerformed
        DefaultTableModel tbn = (DefaultTableModel) table_ctdondh.getModel();
        tbn.setRowCount(0);
        jcb_tenhang.removeAllItems();
        Form_load_tenhang();
        jcb_sodh.removeAllItems();
        Form_load_sodh();
        hienthi_ctdondh();
    }//GEN-LAST:event_btn_dulieugoc_ctdondhActionPerformed

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        DefaultTableModel tbn = (DefaultTableModel) table_ctdondh.getModel();
        tbn.setRowCount(0);
        jcb_tenhang.removeAllItems();
        Form_load_tenhang();
        jcb_sodh.removeAllItems();
        Form_load_sodh();
        hienthi_ctdondh();
    }//GEN-LAST:event_jPanel2ComponentShown

    private void table_ctdondhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_ctdondhMouseClicked
        int index = table_ctdondh.getSelectedRow();
        jcb_sodh.setSelectedItem(table_ctdondh.getValueAt(index, 0).toString());
        jcb_tenhang.setSelectedItem(table_ctdondh.getValueAt(index, 1).toString());
        tf_soluongdat.setText(table_ctdondh.getValueAt(index, 2).toString());
    }//GEN-LAST:event_table_ctdondhMouseClicked

    private void btn_them_ctdondhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_them_ctdondhActionPerformed
        add_ctdondh();
    }//GEN-LAST:event_btn_them_ctdondhActionPerformed

    private void btn_update_ctdondhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_ctdondhActionPerformed
        Update_ctdondh();
    }//GEN-LAST:event_btn_update_ctdondhActionPerformed

    private void btn_delete_ctdondhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_ctdondhActionPerformed
        Delete_ctdondh();
    }//GEN-LAST:event_btn_delete_ctdondhActionPerformed

    private void btn_thoat_ctdondhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoat_ctdondhActionPerformed
        this.setVisible(false);
        new mainInterface().setVisible(true);
    }//GEN-LAST:event_btn_thoat_ctdondhActionPerformed

    private void btn_thoat_ctdondh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoat_ctdondh1ActionPerformed
        this.setVisible(false);
        new mainInterface().setVisible(true);
    }//GEN-LAST:event_btn_thoat_ctdondh1ActionPerformed

    private void btn_tim_sodhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tim_sodhActionPerformed
       DefaultTableModel tbn=(DefaultTableModel) table_ctdondh.getModel();
       tbn.setRowCount(0);
        tim_soDH();
    }//GEN-LAST:event_btn_tim_sodhActionPerformed

    private void btn_tim_tenhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tim_tenhangActionPerformed
         DefaultTableModel tbn=(DefaultTableModel) table_ctdondh.getModel();
       tbn.setRowCount(0);
        tim_tenHang();
    }//GEN-LAST:event_btn_tim_tenhangActionPerformed

    private void btn_tim_soDH_tenHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tim_soDH_tenHangActionPerformed
        DefaultTableModel tbn=(DefaultTableModel) table_ctdondh.getModel();
       tbn.setRowCount(0);
        tim_soDH_tenHang();
                   
    }//GEN-LAST:event_btn_tim_soDH_tenHangActionPerformed

    /**
     * @param args the command line arguments
     */
    //Don Dat Hang
    public void hienthi() {
        DefaultTableModel tbn = (DefaultTableModel) table_dondh.getModel();
        try {
            String query = "select DONDH.SoDh,DONDH.NgayDh,NHACC.TenNhaCc from DONDH inner join NHACC on DONDH.MaNhaCc=NHACC.MaNhaCc order by DONDH.SoDh asc";
            Connection conn = DAO.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector vt = new Vector();
                vt.add(rs.getString("DONDH.SoDh"));
                vt.add(rs.getString("DONDH.NgayDh"));
                vt.add(rs.getString("NHACC.TenNhaCc"));
                tbn.addRow(vt);
            }
            table_dondh.setModel(tbn);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public String getMaNhaCc(String tenncc) {
        String mancc = "";
        try {
            String query = "select MaNhaCc from NHACC where TenNhaCc=?";
            Connection conn = DAO.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, tenncc);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {

                mancc = rs.getString(1);
            }

        } catch (Exception e) {
            System.out.println(e);
        }
        return mancc;
    }

    public void Form_load_TenNhaCc() {

        try {
            String query = "select TenNhaCc from NHACC order by TenNhaCc asc";
            Connection conn = DAO.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                jcb_tenncc.addItem(rs.getString("TenNhaCc"));
            }
        } catch (Exception e) {
        }
    }

    public void Add_DONDH() {
        DefaultTableModel tbn = (DefaultTableModel) table_dondh.getModel();
        try {
            String query = "insert into DONDH values(?,?,?)";
            Connection conn = DAO.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-mm-dd");
            Date date = new SimpleDateFormat("dd/mm/yyyy").parse(tf_ngaydh.getText());
            String strDate = formatter.format(date);
            ps.setString(2, strDate);
            ps.setString(3, getMaNhaCc(jcb_tenncc.getSelectedItem().toString()));
            ps.setString(1, tf_sohd.getText());
            int check = ps.executeUpdate();
            if (check > 0) {
                tf_sohd.setText("");
                tf_ngaydh.setText("");
                tbn.setRowCount(0);
                hienthi();
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Không thêm được!");
            }
        } catch (Exception e) {
        }
    }

    public void Update_DONDH() {
        DefaultTableModel tbn = (DefaultTableModel) table_dondh.getModel();
        try {
            String query = "Update DONDH set NgayDh=?,MaNhaCc=? where SoDh=?";
            Connection conn = DAO.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-mm-dd");
            Date date = new SimpleDateFormat("dd/mm/yyyy").parse(tf_ngaydh.getText());
            String strDate = formatter.format(date);
            ps.setString(1, strDate);
            ps.setString(2, getMaNhaCc(jcb_tenncc.getSelectedItem().toString()));
            ps.setString(3, tf_sohd.getText());
            int check = ps.executeUpdate();
            if (check > 0) {

                tbn.setRowCount(0);
                hienthi();
                JOptionPane.showMessageDialog(this, "Sửa thành công");

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void Delete_DONDH() {
        DefaultTableModel tbn = (DefaultTableModel) table_dondh.getModel();
        try {
            String query = "delete from DONDH where SoDh=?";
            Connection conn = DAO.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, tf_sohd.getText());

            if (JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa đơn hàng " + tf_sohd.getText() + " này?", "Confirm", JOptionPane.YES_NO_OPTION)
                    == JOptionPane.YES_OPTION) {
                int check = ps.executeUpdate();
                if (check > 0) {
                    tbn.setRowCount(0);
                    hienthi();
                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại!");
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    //Chi tiet don dat hang
    public void hienthi_ctdondh() {
        DefaultTableModel tbn = (DefaultTableModel) table_ctdondh.getModel();
        try {
            String query = "select CTDONDH.SoDh,SANPHAM.TenSP,CTDONDH.SlDat from CTDONDH inner join SANPHAM on CTDONDH.MaSP=SANPHAM.MaSP order by CTDONDH.SoDh asc";
            Connection conn = DAO.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector vt = new Vector();
                vt.add(rs.getString(1));
                vt.add(rs.getString(2));
                vt.add(rs.getString(3));
                tbn.addRow(vt);
            }
            table_ctdondh.setModel(tbn);
        } catch (Exception e) {
        }
    }

    public String getMasp(String tenh) {
        String masp = "";
        try {
            String query = "select MaSP from SANPHAM where TenSP=? order by MaSP asc";
            Connection conn = DAO.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, tenh);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                masp = rs.getString("MaSP");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return masp;
    }

    public void Form_load_sodh() {
        try {
            String query = "select SoDh from DONDH order by SoDh asc";
            Connection conn = DAO.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                jcb_sodh.addItem(rs.getString("SoDh"));
            }
        } catch (Exception e) {
        }
    }

    public void Form_load_tenhang() {
        try {
            String query = "select TenSP from SANPHAM order by TenSP asc";
            Connection conn = DAO.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                jcb_tenhang.addItem(rs.getString(1));
            }
        } catch (Exception e) {
        }
    }

    public void add_ctdondh() {
        DefaultTableModel tbn = (DefaultTableModel) table_ctdondh.getModel();
        try {
            String query = "insert into CTDONDH values(?,?,?)";
            Connection conn = DAO.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, jcb_sodh.getSelectedItem().toString());
            ps.setString(2, getMasp(jcb_tenhang.getSelectedItem().toString()));
            ps.setString(3, tf_soluongdat.getText());
            int check = ps.executeUpdate();
            if (check > 0) {
                tf_soluongdat.setText("");
                tbn.setRowCount(0);
                hienthi_ctdondh();
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
                System.out.println(check);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Thêm thất bại do sản phẩm đã tồn tại!");
            System.out.println(e);
        }
    }

    public void Update_ctdondh() {
        DefaultTableModel tbn = (DefaultTableModel) table_ctdondh.getModel();
        try {
            String query = "update CTDONDH set SlDat=? where SoDh=? and MaSP=?";
            Connection conn = DAO.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, tf_soluongdat.getText());
            ps.setString(2, jcb_sodh.getSelectedItem().toString());
            ps.setString(3, getMasp(jcb_tenhang.getSelectedItem().toString()));
            int check = ps.executeUpdate();
            if (check > 0) {
                tbn.setRowCount(0);
                hienthi_ctdondh();
                JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Không cập nhật được sản phẩm!");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void Delete_ctdondh() {
        DefaultTableModel tbn = (DefaultTableModel) table_ctdondh.getModel();
        try {
            String query = "delete from CTDONDH where SoDh=? and MaSP=?";
            Connection conn = DAO.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, jcb_sodh.getSelectedItem().toString());
            ps.setString(2, getMasp(jcb_tenhang.getSelectedItem().toString()));
            if (JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa số hóa đơn " + jcb_sodh.getSelectedItem() + " này?", "Confirm", JOptionPane.YES_NO_OPTION)
                    == JOptionPane.YES_OPTION) {
                int check = ps.executeUpdate();
                if (check > 0) {
                    tbn.setRowCount(0);
                    hienthi_ctdondh();
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void tim_soDH() {
        DefaultTableModel tbn =(DefaultTableModel) table_ctdondh.getModel();;
        
        try {
            String query = "select CTDONDH.SoDh,SANPHAM.TenSP,CTDONDH.SlDat from CTDONDH inner join SANPHAM on CTDONDH.MaSP=SANPHAM.MaSP where CTDONDH.SoDh=? order by CTDONDH.SoDh asc";
            Connection conn = DAO.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, jcb_sodh.getSelectedItem().toString());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector vt = new Vector();
                 vt.add(rs.getString("CTDONDH.SoDh"));
                 vt.add(rs.getString("SANPHAM.TenSP"));
                 vt.add(rs.getString("CTDONDH.SlDat"));
                 tbn.addRow(vt);
            }
            table_ctdondh.setModel(tbn);
        } catch (Exception e) {
        }
    }
    public void tim_tenHang() {
        DefaultTableModel tbn =(DefaultTableModel) table_ctdondh.getModel();;
        
        try {
            String query = "select CTDONDH.SoDh,SANPHAM.TenSP,CTDONDH.SlDat from CTDONDH inner join SANPHAM on CTDONDH.MaSP=SANPHAM.MaSP where CTDONDH.MaSP=? order by CTDONDH.SoDh asc";
            Connection conn = DAO.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, getMasp(jcb_tenhang.getSelectedItem().toString()));
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector vt = new Vector();
                 vt.add(rs.getString("CTDONDH.SoDh"));
                 vt.add(rs.getString("SANPHAM.TenSP"));
                 vt.add(rs.getString("CTDONDH.SlDat"));
                 tbn.addRow(vt);
            }
            table_ctdondh.setModel(tbn);
        } catch (Exception e) {
        }
    }
    public void tim_soDH_tenHang() {
        DefaultTableModel tbn =(DefaultTableModel) table_ctdondh.getModel();;
        
        try {
            String query = "select CTDONDH.SoDh,SANPHAM.TenSP,CTDONDH.SlDat from CTDONDH inner join SANPHAM on CTDONDH.MaSP=SANPHAM.MaSP where CTDONDH.MaSP=? and CTDONDH.SoDh=? order by CTDONDH.SoDh asc";
            Connection conn = DAO.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, getMasp(jcb_tenhang.getSelectedItem().toString()));
            ps.setString(2, jcb_sodh.getSelectedItem().toString());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector vt = new Vector();
                 vt.add(rs.getString("CTDONDH.SoDh"));
                 vt.add(rs.getString("SANPHAM.TenSP"));
                 vt.add(rs.getString("CTDONDH.SlDat"));
                 tbn.addRow(vt);
            }
            table_ctdondh.setModel(tbn);
        } catch (Exception e) {
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDonDh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDonDh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDonDh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDonDh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLDonDh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete_ctdondh;
    private javax.swing.JButton btn_dulieugoc_ctdondh;
    private javax.swing.JButton btn_dulieugoc_dondh;
    private javax.swing.JButton btn_them_ctdondh;
    private javax.swing.JButton btn_them_dondh;
    private javax.swing.JButton btn_thoat_ctdondh;
    private javax.swing.JButton btn_thoat_ctdondh1;
    private javax.swing.JButton btn_tim_dondh;
    private javax.swing.JButton btn_tim_soDH_tenHang;
    private javax.swing.JButton btn_tim_sodh;
    private javax.swing.JButton btn_tim_tenhang;
    private javax.swing.JButton btn_update_ctdondh;
    private javax.swing.JButton btn_update_dondh;
    private javax.swing.JButton btn_xoa_dondh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox jcb_sodh;
    private javax.swing.JComboBox jcb_tenhang;
    private javax.swing.JComboBox jcb_tenncc;
    private javax.swing.JTable table_ctdondh;
    private javax.swing.JTable table_dondh;
    private javax.swing.JTextField tf_ngaydh;
    private javax.swing.JTextField tf_sohd;
    private javax.swing.JTextField tf_soluongdat;
    // End of variables declaration//GEN-END:variables
}
