/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btl_java;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Timkiem_SANPHAM extends javax.swing.JFrame {

    /**
     * Creates new form Timkiem_SANPHAM
     */
    public Timkiem_SANPHAM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_sp = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_masp = new javax.swing.JTextField();
        tf_tensp = new javax.swing.JTextField();
        tf_mausac = new javax.swing.JTextField();
        tf_donvitinh = new javax.swing.JTextField();
        btn_tim_masp = new javax.swing.JButton();
        btn_tim_tensp = new javax.swing.JButton();
        btn_tim_mausac = new javax.swing.JButton();
        btn_tim_dvTinh = new javax.swing.JButton();
        btn_tim_tenloai = new javax.swing.JButton();
        btn_dulieugoc_timSP = new javax.swing.JButton();
        btn_thoat_tim_sp = new javax.swing.JButton();
        jcb_tenloai = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TÌM KIẾM MẶT HÀNG");

        table_sp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Màu sắc", "Đơn vị tính", "Tên loại"
            }
        ));
        table_sp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_spMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_sp);

        jLabel2.setText("Mã SP");

        jLabel3.setText("Tên SP");

        jLabel4.setText("Màu Sắc");

        jLabel5.setText("Đơn vị tính");

        jLabel6.setText("Tên loại");

        btn_tim_masp.setText("Lọc theo mã");
        btn_tim_masp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tim_maspActionPerformed(evt);
            }
        });

        btn_tim_tensp.setText("Lọc theo tên sp");
        btn_tim_tensp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tim_tenspActionPerformed(evt);
            }
        });

        btn_tim_mausac.setText("Lọc theo màu sắc");
        btn_tim_mausac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tim_mausacActionPerformed(evt);
            }
        });

        btn_tim_dvTinh.setText("Lọc theo đơn vị tính");
        btn_tim_dvTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tim_dvTinhActionPerformed(evt);
            }
        });

        btn_tim_tenloai.setText("Lọc theo tên loại");
        btn_tim_tenloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tim_tenloaiActionPerformed(evt);
            }
        });

        btn_dulieugoc_timSP.setText("Dữ liệu gốc");
        btn_dulieugoc_timSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dulieugoc_timSPActionPerformed(evt);
            }
        });

        btn_thoat_tim_sp.setText("Thoát");
        btn_thoat_tim_sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoat_tim_spActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_masp)
                            .addComponent(tf_tensp)
                            .addComponent(tf_mausac)
                            .addComponent(tf_donvitinh)
                            .addComponent(jcb_tenloai, 0, 182, Short.MAX_VALUE))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_tim_dvTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_tim_masp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_tim_tensp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_tim_mausac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_tim_tenloai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_dulieugoc_timSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_thoat_tim_sp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_masp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tim_masp)
                    .addComponent(btn_dulieugoc_timSP))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_tensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tim_tensp)
                    .addComponent(btn_thoat_tim_sp))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_mausac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tim_mausac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_donvitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tim_dvTinh))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btn_tim_tenloai)
                    .addComponent(jcb_tenloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_spMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_spMouseClicked
        int index=table_sp.getSelectedRow();
        tf_masp.setText(table_sp.getValueAt(index, 0).toString());
        tf_tensp.setText(table_sp.getValueAt(index, 1).toString());
        tf_mausac.setText(table_sp.getValueAt(index,2).toString());
        tf_donvitinh.setText(table_sp.getValueAt(index, 3).toString());
        jcb_tenloai.setSelectedItem(table_sp.getValueAt(index, 4));
    }//GEN-LAST:event_table_spMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        DefaultTableModel tbn=(DefaultTableModel) table_sp.getModel();
        tbn.setRowCount(0);
        jcb_tenloai.removeAllItems();
        Form_comboBox_loaiSP();
        Form_load_SANPHAM();
    }//GEN-LAST:event_formComponentShown

    private void btn_dulieugoc_timSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dulieugoc_timSPActionPerformed
        DefaultTableModel tbn=(DefaultTableModel) table_sp.getModel();
        tbn.setRowCount(0);
        jcb_tenloai.removeAllItems();
        Form_comboBox_loaiSP();
        Form_load_SANPHAM();
    }//GEN-LAST:event_btn_dulieugoc_timSPActionPerformed

    private void btn_tim_maspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tim_maspActionPerformed
       DefaultTableModel tbn=(DefaultTableModel) table_sp.getModel();
       tbn.setRowCount(0);
        Tim_maSP();
    }//GEN-LAST:event_btn_tim_maspActionPerformed

    private void btn_thoat_tim_spActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoat_tim_spActionPerformed
        this.setVisible(false);
        new QLSanPham().setVisible(true);
    }//GEN-LAST:event_btn_thoat_tim_spActionPerformed

    private void btn_tim_tenspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tim_tenspActionPerformed
        DefaultTableModel tbn=(DefaultTableModel) table_sp.getModel();
       tbn.setRowCount(0);
       Tim_tenSP();
    }//GEN-LAST:event_btn_tim_tenspActionPerformed

    private void btn_tim_mausacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tim_mausacActionPerformed
        DefaultTableModel tbn=(DefaultTableModel) table_sp.getModel();
       tbn.setRowCount(0);
       Tim_mausacSP();
    }//GEN-LAST:event_btn_tim_mausacActionPerformed

    private void btn_tim_dvTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tim_dvTinhActionPerformed
        DefaultTableModel tbn=(DefaultTableModel) table_sp.getModel();
       tbn.setRowCount(0);
       Tim_donvitinhSP();
    }//GEN-LAST:event_btn_tim_dvTinhActionPerformed

    private void btn_tim_tenloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tim_tenloaiActionPerformed
        DefaultTableModel tbn=(DefaultTableModel) table_sp.getModel();
       tbn.setRowCount(0);
       Tim_tenloaiSP();
    }//GEN-LAST:event_btn_tim_tenloaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public void Form_load_SANPHAM(){
        DefaultTableModel tbn=(DefaultTableModel) table_sp.getModel();
        try {
            String query="select SANPHAM.MaSp,SANPHAM.TenSP,SANPHAM.MauSac,SANPHAM.DvTinh,LOAISP.Tenloai from SANPHAM inner join LOAISP on SANPHAM.Maloai=LOAISP.Maloai";
            Connection conn=DAO.getConnection();
            PreparedStatement ps=conn.prepareStatement(query);
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                Vector vt=new Vector();
                vt.add(rs.getString("SANPHAM.MaSp"));
                vt.add(rs.getString("SANPHAM.TenSP"));
                vt.add(rs.getString("SANPHAM.MauSac"));
                vt.add(rs.getString("SANPHAM.DvTinh"));
                vt.add(rs.getString("LOAISP.Tenloai"));
                tbn.addRow(vt);
                
                
            }
            table_sp.setModel(tbn);
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    public String getMaloaisp(String tenloai){
        String maloai="";
        try {
            String query="select Maloai from LOAISP where Tenloai=?";
            Connection conn=DAO.getConnection();
            PreparedStatement ps=conn.prepareStatement(query);
            ps.setString(1,tenloai);
            ResultSet rs=ps.executeQuery();
           while(rs.next()){
           maloai=rs.getString("Maloai");
           }
            
        } catch (Exception e) {
            System.out.println(e);
        }
        return maloai;
    }
    public void Form_comboBox_loaiSP(){
         
        try {
            String query="select Tenloai from LOAISP";
            Connection conn=DAO.getConnection();
            PreparedStatement ps=conn.prepareStatement(query);
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                jcb_tenloai.addItem(rs.getString("LOAISP.Tenloai")); 
            }
           
            
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
    
    public void Tim_maSP(){
        DefaultTableModel tbn=(DefaultTableModel) table_sp.getModel();
        try {
            String query="select SANPHAM.MaSp,SANPHAM.TenSP,SANPHAM.MauSac,SANPHAM.DvTinh,LOAISP.Tenloai from SANPHAM inner join LOAISP on SANPHAM.Maloai=LOAISP.Maloai where SANPHAM.MaSP=?";
            Connection conn=DAO.getConnection();
            PreparedStatement ps=conn.prepareStatement(query);
            ps.setString(1,tf_masp.getText());
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                Vector vt=new Vector();
                vt.add(rs.getString("SANPHAM.MaSp"));
                vt.add(rs.getString("SANPHAM.TenSP"));
                vt.add(rs.getString("SANPHAM.MauSac"));
                vt.add(rs.getString("SANPHAM.DvTinh"));
                vt.add(rs.getString("LOAISP.Tenloai"));
                tbn.addRow(vt);  
            }
            table_sp.setModel(tbn);
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    public void Tim_tenSP(){
        DefaultTableModel tbn=(DefaultTableModel) table_sp.getModel();
        try {
            String query="select SANPHAM.MaSp,SANPHAM.TenSP,SANPHAM.MauSac,SANPHAM.DvTinh,LOAISP.Tenloai from SANPHAM inner join LOAISP on SANPHAM.Maloai=LOAISP.Maloai where SANPHAM.TenSP like ?";
            Connection conn=DAO.getConnection();
            PreparedStatement ps=conn.prepareStatement(query);
            ps.setString(1,"%"+tf_tensp.getText()+"%");
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                Vector vt=new Vector();
                vt.add(rs.getString("SANPHAM.MaSp"));
                vt.add(rs.getString("SANPHAM.TenSP"));
                vt.add(rs.getString("SANPHAM.MauSac"));
                vt.add(rs.getString("SANPHAM.DvTinh"));
                vt.add(rs.getString("LOAISP.Tenloai"));
                tbn.addRow(vt);  
            }
            table_sp.setModel(tbn);
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    public void Tim_mausacSP(){
        DefaultTableModel tbn=(DefaultTableModel) table_sp.getModel();
        try {
            String query="select SANPHAM.MaSp,SANPHAM.TenSP,SANPHAM.MauSac,SANPHAM.DvTinh,LOAISP.Tenloai from SANPHAM inner join LOAISP on SANPHAM.Maloai=LOAISP.Maloai where SANPHAM.MauSac like ?";
            Connection conn=DAO.getConnection();
            PreparedStatement ps=conn.prepareStatement(query);
            ps.setString(1,"%"+tf_mausac.getText()+"%");
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                Vector vt=new Vector();
                vt.add(rs.getString("SANPHAM.MaSp"));
                vt.add(rs.getString("SANPHAM.TenSP"));
                vt.add(rs.getString("SANPHAM.MauSac"));
                vt.add(rs.getString("SANPHAM.DvTinh"));
                vt.add(rs.getString("LOAISP.Tenloai"));
                tbn.addRow(vt);  
            }
            table_sp.setModel(tbn);
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    public void Tim_donvitinhSP(){
        DefaultTableModel tbn=(DefaultTableModel) table_sp.getModel();
        try {
            String query="select SANPHAM.MaSp,SANPHAM.TenSP,SANPHAM.MauSac,SANPHAM.DvTinh,LOAISP.Tenloai from SANPHAM inner join LOAISP on SANPHAM.Maloai=LOAISP.Maloai where SANPHAM.DvTinh like ?";
            Connection conn=DAO.getConnection();
            PreparedStatement ps=conn.prepareStatement(query);
            ps.setString(1,"%"+tf_donvitinh.getText()+"%");
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                Vector vt=new Vector();
                vt.add(rs.getString("SANPHAM.MaSp"));
                vt.add(rs.getString("SANPHAM.TenSP"));
                vt.add(rs.getString("SANPHAM.MauSac"));
                vt.add(rs.getString("SANPHAM.DvTinh"));
                vt.add(rs.getString("LOAISP.Tenloai"));
                tbn.addRow(vt);  
            }
            table_sp.setModel(tbn);
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    public void Tim_tenloaiSP(){
        DefaultTableModel tbn=(DefaultTableModel) table_sp.getModel();
        try {
            String query="select SANPHAM.MaSp,SANPHAM.TenSP,SANPHAM.MauSac,SANPHAM.DvTinh,LOAISP.Tenloai from SANPHAM inner join LOAISP on SANPHAM.Maloai=LOAISP.Maloai where LOAISP.Tenloai=?";
            Connection conn=DAO.getConnection();
            PreparedStatement ps=conn.prepareStatement(query);
            ps.setString(1,jcb_tenloai.getSelectedItem().toString());
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                Vector vt=new Vector();
                vt.add(rs.getString("SANPHAM.MaSp"));
                vt.add(rs.getString("SANPHAM.TenSP"));
                vt.add(rs.getString("SANPHAM.MauSac"));
                vt.add(rs.getString("SANPHAM.DvTinh"));
                vt.add(rs.getString("LOAISP.Tenloai"));
                tbn.addRow(vt);  
            }
            table_sp.setModel(tbn);
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Timkiem_SANPHAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Timkiem_SANPHAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Timkiem_SANPHAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Timkiem_SANPHAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Timkiem_SANPHAM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dulieugoc_timSP;
    private javax.swing.JButton btn_thoat_tim_sp;
    private javax.swing.JButton btn_tim_dvTinh;
    private javax.swing.JButton btn_tim_masp;
    private javax.swing.JButton btn_tim_mausac;
    private javax.swing.JButton btn_tim_tenloai;
    private javax.swing.JButton btn_tim_tensp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jcb_tenloai;
    private javax.swing.JTable table_sp;
    private javax.swing.JTextField tf_donvitinh;
    private javax.swing.JTextField tf_masp;
    private javax.swing.JTextField tf_mausac;
    private javax.swing.JTextField tf_tensp;
    // End of variables declaration//GEN-END:variables
}
