/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btl_java;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Timkiem_NHACC extends javax.swing.JFrame {

    /**
     * Creates new form Timkiem_NHACC
     */
    public Timkiem_NHACC() {
        initComponents();
        Form_load_NCC();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_ncc = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_mancc = new javax.swing.JTextField();
        tf_tenncc = new javax.swing.JTextField();
        tf_diachincc = new javax.swing.JTextField();
        tf_sdtncc = new javax.swing.JTextField();
        btn_tim_mancc = new javax.swing.JButton();
        btn_tim_tenncc = new javax.swing.JButton();
        btn_tim_diachincc = new javax.swing.JButton();
        btn_tim_sdtncc = new javax.swing.JButton();
        btn_dulieugoc = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_ncc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NCC", "Tên NCC", "Địa chỉ", "Số điện thoại"
            }
        ));
        jTable_ncc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_nccMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_ncc);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TÌM KIẾM NHÀ CUNG CẤP");

        jLabel2.setText("Mã NCC");

        jLabel3.setText("Tên NCC");

        jLabel4.setText("Địa chỉ");

        jLabel5.setText("SĐT");

        btn_tim_mancc.setText("Lọc theo mã ncc");
        btn_tim_mancc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tim_manccActionPerformed(evt);
            }
        });

        btn_tim_tenncc.setText("Lọc theo tên ncc");
        btn_tim_tenncc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tim_tennccActionPerformed(evt);
            }
        });

        btn_tim_diachincc.setText("Lọc theo địa chỉ");
        btn_tim_diachincc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tim_diachinccActionPerformed(evt);
            }
        });

        btn_tim_sdtncc.setText("Lọc theo SĐT");
        btn_tim_sdtncc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tim_sdtnccActionPerformed(evt);
            }
        });

        btn_dulieugoc.setText("Dữ liệu gốc");
        btn_dulieugoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dulieugocActionPerformed(evt);
            }
        });

        btn_thoat.setText("Thoát");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_tenncc)
                            .addComponent(tf_diachincc)
                            .addComponent(tf_sdtncc, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(tf_mancc)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btn_tim_mancc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(btn_tim_tenncc)))
                .addGap(18, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_tim_diachincc)
                        .addGap(99, 99, 99)
                        .addComponent(btn_tim_sdtncc)
                        .addGap(77, 77, 77)
                        .addComponent(btn_dulieugoc)))
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(btn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(tf_mancc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(tf_tenncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addComponent(jLabel4))
                            .addComponent(tf_diachincc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_sdtncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tim_mancc)
                    .addComponent(btn_tim_tenncc)
                    .addComponent(btn_tim_diachincc)
                    .addComponent(btn_tim_sdtncc)
                    .addComponent(btn_dulieugoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        this.setVisible(false);
        new QLSanPham().setVisible(true);
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void jTable_nccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_nccMouseClicked
        int index=jTable_ncc.getSelectedRow();
        tf_mancc.setText(jTable_ncc.getValueAt(index, 0).toString());
        tf_tenncc.setText(jTable_ncc.getValueAt(index, 1).toString());
        tf_diachincc.setText(jTable_ncc.getValueAt(index, 2).toString());
        tf_sdtncc.setText(jTable_ncc.getValueAt(index, 3).toString());
    }//GEN-LAST:event_jTable_nccMouseClicked

    private void btn_tim_manccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tim_manccActionPerformed
        DefaultTableModel tbn=(DefaultTableModel) jTable_ncc.getModel();
        tbn.setRowCount(0);
        Search_MANCC();
    }//GEN-LAST:event_btn_tim_manccActionPerformed

    private void btn_tim_tennccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tim_tennccActionPerformed
        DefaultTableModel tbn=(DefaultTableModel) jTable_ncc.getModel();
        tbn.setRowCount(0);
        Timkiem_tenNCC();
    }//GEN-LAST:event_btn_tim_tennccActionPerformed

    private void btn_tim_diachinccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tim_diachinccActionPerformed
        DefaultTableModel tbn=(DefaultTableModel) jTable_ncc.getModel();
        tbn.setRowCount(0);
        Timkiem_diachiNCC();
    }//GEN-LAST:event_btn_tim_diachinccActionPerformed

    private void btn_tim_sdtnccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tim_sdtnccActionPerformed
       DefaultTableModel tbn=(DefaultTableModel) jTable_ncc.getModel();
        tbn.setRowCount(0);
        Timkiem_sdtNCC();
    }//GEN-LAST:event_btn_tim_sdtnccActionPerformed

    private void btn_dulieugocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dulieugocActionPerformed
        DefaultTableModel tbn=(DefaultTableModel) jTable_ncc.getModel();
        tbn.setRowCount(0);
        Form_load_NCC();
    }//GEN-LAST:event_btn_dulieugocActionPerformed

    /**
     * @param args the command line arguments
     */
    public void Form_load_NCC() {
        DefaultTableModel tbNCC = (DefaultTableModel) jTable_ncc.getModel();
        try {
//           
            String query = "Select * from NHACC";
            Connection cn = DAO.getConnection();
            PreparedStatement ps = cn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                Vector vector = new Vector();
                vector.add(rs.getString("MaNhaCc"));
                vector.add(rs.getString("TenNhaCc"));
                vector.add(rs.getString("DiaChi"));
                vector.add(rs.getString("DienThoai"));
                
                tbNCC.addRow(vector);

            }
            jTable_ncc.setModel(tbNCC);
            
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    public void Search_MANCC(){
        DefaultTableModel tbn = (DefaultTableModel) jTable_ncc.getModel();
        try {         
            String query = "Select * from NHACC where MaNhaCc=?";
            Connection cn = DAO.getConnection();
            PreparedStatement ps = cn.prepareStatement(query);
             ps.setString(1,tf_mancc.getText());
            ResultSet rs = ps.executeQuery();
           
            while (rs.next()) {
                Vector vector = new Vector();
                vector.add(rs.getString("MaNhacc"));
                vector.add(rs.getString("TenNhaCc"));
                vector.add(rs.getString("DiaChi"));
                vector.add(rs.getString("DienThoai"));
                tbn.addRow(vector);

            }
            jTable_ncc.setModel(tbn);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void Timkiem_tenNCC(){
      DefaultTableModel tbn = (DefaultTableModel) jTable_ncc.getModel();
        try {         
            String query = "Select * from NHACC where TenNhaCc like ?";
            Connection cn = DAO.getConnection();
            PreparedStatement ps = cn.prepareStatement(query);
             ps.setString(1,"%"+tf_tenncc.getText()+"%");
            ResultSet rs = ps.executeQuery();
           
            while (rs.next()) {
                Vector vector = new Vector();
                vector.add(rs.getString("MaNhaCc"));
                vector.add(rs.getString("TenNhaCc"));
                vector.add(rs.getString("DiaChi"));
                vector.add(rs.getString("DienThoai"));
                tbn.addRow(vector);

            }
            jTable_ncc.setModel(tbn);

        } catch (Exception e) {
            e.printStackTrace();
        }
     }
    public void Timkiem_sdtNCC(){
      DefaultTableModel tbn = (DefaultTableModel) jTable_ncc.getModel();
        try {         
            String query = "Select * from NHACC where DienThoai =?";
            Connection cn = DAO.getConnection();
            PreparedStatement ps = cn.prepareStatement(query);
             ps.setString(1,tf_sdtncc.getText());
            ResultSet rs = ps.executeQuery();
           
            while (rs.next()) {
                Vector vector = new Vector();
                vector.add(rs.getString("MaNhaCc"));
                vector.add(rs.getString("TenNhaCc"));
                vector.add(rs.getString("DiaChi"));
                vector.add(rs.getString("DienThoai"));
                tbn.addRow(vector);

            }
            jTable_ncc.setModel(tbn);

        } catch (Exception e) {
            e.printStackTrace();
        }
     }
    public void Timkiem_diachiNCC(){
      DefaultTableModel tbn = (DefaultTableModel) jTable_ncc.getModel();
        try {         
            String query = "Select * from NHACC where DiaChi like ?";
            Connection cn = DAO.getConnection();
            PreparedStatement ps = cn.prepareStatement(query);
             ps.setString(1,"%"+tf_diachincc.getText()+"%");
            ResultSet rs = ps.executeQuery();
           
            while (rs.next()) {
                Vector vector = new Vector();
                vector.add(rs.getString("MaNhaCc"));
                vector.add(rs.getString("TenNhaCc"));
                vector.add(rs.getString("DiaChi"));
                vector.add(rs.getString("DienThoai"));
                tbn.addRow(vector);

            }
            jTable_ncc.setModel(tbn);

        } catch (Exception e) {
            e.printStackTrace();
        }
     }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Timkiem_NHACC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Timkiem_NHACC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Timkiem_NHACC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Timkiem_NHACC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Timkiem_NHACC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dulieugoc;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_tim_diachincc;
    private javax.swing.JButton btn_tim_mancc;
    private javax.swing.JButton btn_tim_sdtncc;
    private javax.swing.JButton btn_tim_tenncc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_ncc;
    private javax.swing.JTextField tf_diachincc;
    private javax.swing.JTextField tf_mancc;
    private javax.swing.JTextField tf_sdtncc;
    private javax.swing.JTextField tf_tenncc;
    // End of variables declaration//GEN-END:variables
}
