/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btl_java;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Timkiem_DONDH extends javax.swing.JFrame {

    /**
     * Creates new form Timkiem_DONDH
     */
    public Timkiem_DONDH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_dondh = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_ngaybd = new javax.swing.JTextField();
        tf_thangbd = new javax.swing.JTextField();
        tf_nambd = new javax.swing.JTextField();
        tf_ngaykt = new javax.swing.JTextField();
        tf_thangkt = new javax.swing.JTextField();
        tf_namkt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_tim_ngaydh = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tf_sodh = new javax.swing.JTextField();
        btn_tim_SoDh = new javax.swing.JButton();
        btn_tim_tenncc = new javax.swing.JButton();
        btn_dulieugoc_timDONDH = new javax.swing.JButton();
        btn_thoat_timkiemDONDH = new javax.swing.JButton();
        jcb_tenncc = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        table_dondh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số đơn hàng", "Ngày đặt hàng", "Tên NCC"
            }
        ));
        jScrollPane1.setViewportView(table_dondh);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TÌM KIẾM ĐƠN ĐẶT HÀNG");

        jLabel2.setText("Số đơn hàng");

        jLabel3.setText("Ngày bắt đầu");

        jLabel4.setText("Ngày kết thúc");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ngày");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tháng");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Năm");

        btn_tim_ngaydh.setText("Lọc dữ liệu");
        btn_tim_ngaydh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tim_ngaydhActionPerformed(evt);
            }
        });

        jLabel8.setText("Tên NCC");

        btn_tim_SoDh.setText("Lọc theo số đơn hàng");
        btn_tim_SoDh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tim_SoDhActionPerformed(evt);
            }
        });

        btn_tim_tenncc.setText("Lọc theo tên NCC");
        btn_tim_tenncc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tim_tennccActionPerformed(evt);
            }
        });

        btn_dulieugoc_timDONDH.setText("Dữ liệu gốc");
        btn_dulieugoc_timDONDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dulieugoc_timDONDHActionPerformed(evt);
            }
        });

        btn_thoat_timkiemDONDH.setText("Thoát");
        btn_thoat_timkiemDONDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoat_timkiemDONDHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_sodh)
                                    .addComponent(jcb_tenncc, 0, 158, Short.MAX_VALUE))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_tim_SoDh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_tim_tenncc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(120, 120, 120)
                                .addComponent(btn_thoat_timkiemDONDH))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_dulieugoc_timDONDH)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_ngaybd)
                                    .addComponent(tf_ngaykt)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_thangkt)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_thangbd))))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_namkt)
                            .addComponent(tf_nambd)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                        .addGap(54, 54, 54)
                        .addComponent(btn_tim_ngaydh))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_ngaybd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_thangbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nambd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_ngaykt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_thangkt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_namkt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tim_ngaydh))
                .addGap(38, 38, 38)
                .addComponent(btn_dulieugoc_timDONDH)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_sodh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tim_SoDh))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jcb_tenncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_tim_tenncc)
                        .addComponent(btn_thoat_timkiemDONDH)))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_thoat_timkiemDONDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoat_timkiemDONDHActionPerformed
        this.setVisible(false);
        new QLDonDh().setVisible(true);
    }//GEN-LAST:event_btn_thoat_timkiemDONDHActionPerformed

    private void btn_dulieugoc_timDONDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dulieugoc_timDONDHActionPerformed
        DefaultTableModel tbn=(DefaultTableModel) table_dondh.getModel();
        tbn.setRowCount(0);
        jcb_tenncc.removeAllItems();
        Form_load_TenNhaCc();
        hienthi();
    }//GEN-LAST:event_btn_dulieugoc_timDONDHActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        DefaultTableModel tbn=(DefaultTableModel) table_dondh.getModel();
        tbn.setRowCount(0);
        jcb_tenncc.removeAllItems();
        Form_load_TenNhaCc();
        hienthi();
    }//GEN-LAST:event_formComponentShown

    private void btn_tim_SoDhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tim_SoDhActionPerformed
        DefaultTableModel tbn=(DefaultTableModel) table_dondh.getModel();
        tbn.setRowCount(0);
        Tim_SoDH();
    }//GEN-LAST:event_btn_tim_SoDhActionPerformed

    private void btn_tim_tennccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tim_tennccActionPerformed
        DefaultTableModel tbn=(DefaultTableModel) table_dondh.getModel();
        tbn.setRowCount(0);
        Tim_TENNCC();
    }//GEN-LAST:event_btn_tim_tennccActionPerformed

    private void btn_tim_ngaydhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tim_ngaydhActionPerformed
        DefaultTableModel tbn=(DefaultTableModel) table_dondh.getModel();
        tbn.setRowCount(0);
        Tim_NgayDh();
    }//GEN-LAST:event_btn_tim_ngaydhActionPerformed

    /**
     * @param args the command line arguments
     */
    public void hienthi() {
        DefaultTableModel tbn = (DefaultTableModel) table_dondh.getModel();
        try {
            String query = "select DONDH.SoDh,DONDH.NgayDh,NHACC.TenNhaCc from DONDH inner join NHACC on DONDH.MaNhaCc=NHACC.MaNhaCc";
            Connection conn = DAO.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector vt = new Vector();
                vt.add(rs.getString("DONDH.SoDh"));
                vt.add(rs.getString("DONDH.NgayDh"));
                vt.add(rs.getString("NHACC.TenNhaCc"));
                tbn.addRow(vt);
            }
            table_dondh.setModel(tbn);
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    public String getMaNhaCc(String tenncc) {
        String mancc = "";
        try {
            String query = "select MaNhaCc from NHACC where TenNhaCc=?";
            Connection conn = DAO.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, tenncc);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {

                mancc = rs.getString(1);
            }

        } catch (Exception e) {
            System.out.println(e);
        }
        return mancc;
    }

    public void Form_load_TenNhaCc() {
        DefaultTableModel tbn = (DefaultTableModel) table_dondh.getModel();
        try {
            String query = "select TenNhaCc from NHACC";
            Connection conn = DAO.getConnection();
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                jcb_tenncc.addItem(rs.getString("TenNhaCc"));
            }
        } catch (Exception e) {
        }
    }
    public void Tim_SoDH(){
        DefaultTableModel tbn=(DefaultTableModel) table_dondh.getModel();
        try {
            String query ="select DONDH.SoDh,DONDH.NgayDh,NHACC.TenNhaCc from DONDH inner join NHACC on DONDH.MaNhaCc=NHACC.MaNhaCc where DONDH.SoDh=?";
            Connection conn=DAO.getConnection();
            PreparedStatement ps=conn.prepareStatement(query);
            ps.setString(1,tf_sodh.getText());
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                Vector vt=new Vector();
                vt.add(rs.getString("DONDH.SoDh"));
                vt.add(rs.getString("DONDH.NgayDh"));
                vt.add(rs.getString("NHACC.TenNhaCc"));
                tbn.addRow(vt);
            }
            table_dondh.setModel(tbn);
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    public void Tim_TENNCC(){
        DefaultTableModel tbn=(DefaultTableModel) table_dondh.getModel();
        try {
            String query ="select DONDH.SoDh,DONDH.NgayDh,NHACC.TenNhaCc from DONDH inner join NHACC on DONDH.MaNhaCc=NHACC.MaNhaCc where NHACC.MaNhaCc=?";
            Connection conn=DAO.getConnection();
            PreparedStatement ps=conn.prepareStatement(query);
            ps.setString(1,getMaNhaCc(jcb_tenncc.getSelectedItem().toString()));
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                Vector vt=new Vector();
                vt.add(rs.getString("DONDH.SoDh"));
                vt.add(rs.getString("DONDH.NgayDh"));
                vt.add(rs.getString("NHACC.TenNhaCc"));
                tbn.addRow(vt);
            }
            table_dondh.setModel(tbn);
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    public void Tim_NgayDh(){
        DefaultTableModel tbn=(DefaultTableModel) table_dondh.getModel();
        try {
            String query ="select DONDH.SoDh,DONDH.NgayDh,NHACC.TenNhaCc from DONDH inner join NHACC on DONDH.MaNhaCc=NHACC.MaNhaCc "
                    + "where DONDH.NgayDh between convert(?,date) and convert(?,date)";
            Connection conn=DAO.getConnection();
            PreparedStatement ps=conn.prepareStatement(query);
            ps.setString(1,tf_nambd.getText()+"-"+tf_thangbd.getText()+"-"+tf_ngaybd.getText());
            ps.setString(2,tf_namkt.getText()+"-"+tf_thangkt.getText()+"-"+tf_ngaykt.getText());
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                Vector vt=new Vector();
                vt.add(rs.getString("DONDH.SoDh"));
                vt.add(rs.getString("DONDH.NgayDh"));
                vt.add(rs.getString("NHACC.TenNhaCc"));
                tbn.addRow(vt);
            }
            table_dondh.setModel(tbn);
            
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Timkiem_DONDH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Timkiem_DONDH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Timkiem_DONDH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Timkiem_DONDH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Timkiem_DONDH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dulieugoc_timDONDH;
    private javax.swing.JButton btn_thoat_timkiemDONDH;
    private javax.swing.JButton btn_tim_SoDh;
    private javax.swing.JButton btn_tim_ngaydh;
    private javax.swing.JButton btn_tim_tenncc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcb_tenncc;
    private javax.swing.JTable table_dondh;
    private javax.swing.JTextField tf_nambd;
    private javax.swing.JTextField tf_namkt;
    private javax.swing.JTextField tf_ngaybd;
    private javax.swing.JTextField tf_ngaykt;
    private javax.swing.JTextField tf_sodh;
    private javax.swing.JTextField tf_thangbd;
    private javax.swing.JTextField tf_thangkt;
    // End of variables declaration//GEN-END:variables
}
